### ISSUE TITLE
Activity feed updates

### ISSUE THREAD

**Issue by sbddesign** [PlebFM/PlebFM#23]
Need to add activity feed updates to the leaderboard as users add songs. This is distinct from the queue. The queue reflects the order of songs, and there may only be room for 10 or so songs on screen. The activity feeds shows user activity as it happens, and it quickly fades away.

We may need an API route for this, and then need to figure out best way to get data in the frontend.

- Regular old polling?
- PubSub?
- Websockets?

**Comment by bnonni** [comment]
@sbddesign I vote either an API route + timeout polling or websockets. Thoughts? Obv the former is probably fastest since there's already API infra to build upon, but the latter would provider a better, more scalable solution long term.

**Comment by bnonni** [comment]
Regardless of the implementation of this issue, it brings up a relevant question: how do we plan on collecting data on activity (i.e. bids being submitted, users joining host session)? Should we consider creating a new collection called `activity` storing different `update` objects? See below. Let's chat about it today.

I propose we create a new `Activity` schema with 2 initial `Update` object types:

```js
const ActivitySchema = new Schema<Update>({
  userId: {
    type: String,
    unique: true,
    required: true,
  },
  firstNym: {
    type: String,
    required: true,
  },
  lastNym: {
    type: String,
    required: true,
  },
  avatar: {
    type: String,
    required: true,
  },
});
```


1. `BidSubmit`
```js
{
    "type": "bid",
    "user": User(),
    "song": Song() (optional),
    "timestamp": "2023-01-07T14:37:47.461Z"
}
```

2. `SessionJoin`
```json
{
    "type": "join",
    "user": User(),
    "timestamp": "2023-01-07T14:37:47.461Z"
}
```

For reference
```js
User
{
  userId: string;
  firstNym: string;
  lastNym: string;
  avatar: string;
  color?: string;
}

Song
{
  duration_ms: number;
  album: { images: { url: string }[]; name: string };
  name: string;
  artists: { name: string }[];
  id: string;
}
```

**Comment by alexlwn123** [comment]
I don't think we need a separate collection to store Activity, as there isn't any new data to store.

Using WebSockets: If the server detects a logged in host, bid updates are sent to the host via the websockets.
Using REST: The host/leaderboard page polls the `getQueue` endpoint on a timer and checks for new bids.

**Comment by bnonni** [comment]
Makes sense. Wasn't sure if we wanted to keep the bid/session join events in a structured way for potential reuse later such as a host view that shows the history of bids and users that joined the session. If that's not something we care about, then your solution is definitely the easier/faster one, which will be much easier to accomplish.

**Comment by bnonni** [comment]
What about when a new user joins the live host session? Do we care about this?

**Comment by bnonni** [comment]
If no new data model(s) are required, and we go with the polling the API option, this becomes more of a frontend issue, so I'll leave that to you two @sbddesign @alexlwn123 

However, I'll continue to work on the websockets since I've made progress and that requires backend/API changes.

**Comment by alexlwn123** [comment]
@bnonni 
> What about when a new user joins the live host session? Do we care about this?

I don't think so... it lets people lurk without feeling spied on

**Comment by bnonni** [comment]
@alexlwn123 

@sbddesign and I discussed this issue and here's the summary:
- /leaderboard/queue route is our source of truth for the current queue state
- as a result, that route is very important and should be its own, standalone route without added complexity or features
- i.e. we think its too important to reuse it for the activity feed updates
- additionally, it doesn't exactly return what we want requiring adding new query params and new logic potentially adding unforeseen side affects and threatening the integrity of our "source of truth"
- at minimum, we need a new route to handle activity feed updates 
- proposal:
    - route name: `/activity`
    - method: GET
    - query params:
        - `hostShortName="atl"`
        - `time="1000"`, where time = amount of milliseconds subtracted for `Date.now()` establishing filter for Plays query
        ```js
             // ?time=1000
             const timestampFilter = Date.now() - 1000
             const updates = await Plays.find({ filter: { queueTimestamp: { $gte: timestampFilter } }})
        ```
    - returns: list of Plays who's queueTimestamp is >= the timestampFilter
    - this allows us to decouple the queue (source of truth) and the activity feed updates while also allowing us to tightly control the window we use to lookback in time

That being said, the further we examine this issue, the more it seems to make sense that we use a separate collection for these updates.

The main rationale is the fact that if we simply reuse the `/queue` route or create a new `/activity` route as outlined above, the front end will be receiving a list of Plays which it will have to do some form of diff checking on to figure out the recently added Plays (i.e. compare whats in queue on frontend to what was received by api call). Using the diff check results, frontend can publish new activity updates on screen. Imo, its bad practice to make the frontend do any form of data mutations on the response object. It should just present what was sent back from the API allowing the backend to handle all data processing.

By creating a new collection, we can cater the data object in it to be exactly what we want allowing us to more easily and succinctly return only the min amount of data the frontend needs to fulfill the func req.

Let us know what you think here. At the very least, I'm going to start a new issue for a new route called /activity, and if you agree with our thinking, I'll implement the new collection per the spec I outlined above.

**Comment by bnonni** [comment]
> @bnonni
> 
> > What about when a new user joins the live host session? Do we care about this?
> 
> I don't think so... it lets people lurk without feeling spied on

Also, @sbddesign and I were talking about this, and realized that the users are all prepopulated nyms, so publishing a session joined update wouldn't dox or reveal any lurkers. The hosts would probably want to see this data after they close their current PlebFM session. It would be like a timeline feed of what happened when.

**Comment by bnonni** [comment]
PR #72

**Comment by bnonni** [comment]
#78 opened to address new data model and collection
