### ISSUE TITLE
Upbid API route

### ISSUE THREAD

**Issue by sbddesign** [PlebFM/PlebFM#32]
We need a way for a user to upbid a route. May be able to work this into the same route as the regular bid with some different query params. Linking that issue for ref: https://github.com/PlebFM/PlebFm/issues/16

**Comment by bnonni** [comment]
@sbddesign is this a v1 or v2 feature? if it's v1, I'll start on it today, but I thought our discussion netted this being a v2 feature.

**Comment by bnonni** [comment]
Closing this issue. Completed in https://github.com/PlebFM/PlebFM/pull/70
