### ISSUE TITLE
Properly capitalize the new repo name

### ISSUE THREAD

**Issue by sbddesign** [PlebFM/PlebFM#33]
Ffs @alexlwn123 this is going to drive me ballistic.

<img width="190" alt="Screen Shot 2022-12-31 at 10 54 33 AM" src="https://user-images.githubusercontent.com/2414177/210148902-6ce8913f-0ebc-4700-89f8-e07f40d4d6ae.png">

<img width="273" alt="Screen Shot 2022-12-31 at 10 55 29 AM" src="https://user-images.githubusercontent.com/2414177/210148926-d3a2089b-5649-4720-8f17-1d44399ec5c7.png">

<img width="131" alt="Screen Shot 2022-12-31 at 10 55 39 AM" src="https://user-images.githubusercontent.com/2414177/210148929-ab4e8a74-1f65-4c86-a929-834326142ee6.png">

**Comment by alexlwn123** [comment]
LGTM!

**Comment by sbddesign** [comment]
Thanks @alexlwn123! You're a fucking beast of an engineer.
