### ISSUE TITLE
Custom favicon

### ISSUE THREAD

**Issue by sbddesign** [PlebFM/PlebFM#48]
Favicon should be zazzy and invoke feelings of delight.

**Comment by sbddesign** [comment]
I have this updated locally, but need to get the self-signed cert and the new local env working so I can test it.

**Comment by alexlwn123** [comment]
@sbddesign 

run “npm install”, then you’ll be able to develop on using “npm run dev” and https://localhost:3000/.

If you’re using brave, you’ll need to change this setting to allow self-signed certs on localhost: 
brave://flags/#allow-insecure-localhost
